###### Packages Needed
##  nginx

- name: Check cert folder exists
  stat:
    path: /etc/letsencrypt/live/{{ reverse_proxy.domain }}/
  register: stat_result

- name: Request a cert with Certbot
  shell:
    cmd: /snap/bin/certbot --nginx -d {{ reverse_proxy.domain }} -d www.{{ reverse_proxy.domain }} --non-interactive --agree-tos -m {{ reverse_proxy.email }}
  when: not stat_result.stat.exists

- name: Setup nginx sites config
  include_tasks:
    file: site-setup-config.yml
  loop: "{{ reverse_proxy.sites }}"

- name: Reload service nginx, in all cases
  systemd_service:
    name: nginx.service
    state: restarted