- name: Check if ArgoCD
  shell:
    cmd: /bin/bash -c "if [[ '{{ item.name }}' == 'argocd' ]]; then echo argo-cd-argocd-server; else echo {{ item.name }}; fi"
  register: svcName

- name: Check if ArgoCD Namespace
  shell:
    cmd: /bin/bash -c "if [[ '{{ item.name }}' == 'argocd' ]]; then echo argocd; else echo default; fi"
  register: svcNamespace

- name: Get Service IP
  shell:
    cmd: /snap/bin/microk8s kubectl get svc {{ svcName.stdout }} -n {{ svcNamespace.stdout }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
  retries: 10
  delay: 6
  register: svcIp
  until: svcIp.rc == 0

- name: Create Nginx Conf file
  template:
    src: site.conf.j2
    dest: /etc/nginx/conf.d/{{ item.name }}.conf