- name: Create users with a home directory
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: "{{ item.name }}"
    create_home: yes
  loop: "{{ users }}"

- name: Ensure users groups exists
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ users }}"
  loop_control:
    loop_var: user
  with_items: "{{ user.groups }}"