- name: Ensure users groups exists
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ users | map(attribute='groups') | flatten }}"

- name: Create users with a home directory
  user:
    name: "{{ item.name }}"
    group: "{{ item.name }}"
    shell: /bin/bash
    create_home: yes
  loop: "{{ users }}"