podman:
  user: test

nextcloud:
  user: "test"
  group: "test"
  image: "nextcloud:31"
  paths:
    data: "/nextcloud/data"
    bin: "/nextcloud/bin"
  bins: 
    - "prestart.sh"
    - "start.sh"