podman:
  user: test

nextcloud:
  user: "test"
  group: "test"
  image: "docker.io/library/nextcloud:31"
  paths:
    data: "/nextcloud/data"
    bin: "/nextcloud/bin"
  bins:
    - "prestart.sh"
    - "start.sh"

container_apps:
  bins:
    - start.sh
    - prestart.sh
    - stop.sh
    - stoppost.sh
  apps_dir: "/opt/container_apps"
  apps:
    - name: ""
      ports: ""
      image: ""
      network: ""
      network_dns: ""
      dirs:
        - ""
      env: ""
      volume: ""
      require: ""
      delay: ""
      cap_add: ""
      restart: ""
      tls_verify: ""
      pull: ""
