users:
  - name: user
    groups:
      - user

packages_apt:
  - net-tools
  - htop
  - fail2ban
  - podman
  - git
  - nginx

packages_snap:
  - microk8s
  - certbot

devops:
  email: test.test@test.com
  user: user
  registry_host: "localhost"   
  registry_port: "32000"
  podman_registries_conf: "/etc/containers/registries.conf"
  apps:
    - name: test
      repo_url: "https://github.com/test/test.git"

github_runner:
  user: user
  group: user
  github_runner_url: "https://api.github.com/repos/actions/runner/releases/latest"
  projects_folder: "/home/user/projects"
  projects:
    - name: test
      repo_url: "https://github.com/test/test.git"
      token: ""

deploy_minecraftum:
  user: runner
  group: runner
  paths:
    root_path: "/opt/minecraftum"
    data_path: "/opt/minecraftum/data"