- name: Installation simple runner server
  hosts: local_runner
  remote_user: root
  become: yes

  roles:
    - users
    - packages
    - github_runner
    - simple_services
    - reverse_proxy