###### Packages Needed
##  git
##  podman

- name: Create minecraft deploy dirs if it does not exist
  file:
    path: "{{ item.value }}"
    state: directory
    mode: '0755'
  loop: "{{ deploy_minecraftum.paths | dict2items }}"

- name: Copy wrapper.sh
  template:
    src: "./wrapper.sh"
    dest: "{{ deploy_minecraftum.paths.root_path }}"
    mode: '0755'

- name: Copy Minecraft Server service file
  template:
    src: ./minecraft-server.service.j2
    dest: /etc/systemd/system/minecraft-server.service

- name: Start and enable the Minecraft Server service
  systemd:
    name: "minecraft-server"
    state: restarted
    daemon_reload: true
    enabled: yes