###### Packages Needed
##  git
##  podman

- name: Create minecraft deploy dirs if it does not exist
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
    mode: '0755'
  loop: "{{ paths | dict2items }}"

- name: Clone docker_images main branch
  ansible.builtin.git:
    repo: https://github.com/K-A-R-I-M/docker_images.git
    dest: "{{ paths.minecraftum_path }}"
    single_branch: yes
    version: main

- name: Get Minecraft server
  ansible.builtin.shell:
    chdir: "{{ paths.minecraftum_path }}/minekraftum/"
    cmd: "./get_minecraft_server.py"

- name: Get Minecraft server
  ansible.builtin.shell:
    chdir: "{{ paths.minecraftum_path }}/minekraftum/"
    cmd: "cp ./server.jar {{ paths.data_path }}"

- name: Remove previous minecraftum container
  ansible.builtin.shell:
    cmd: "podman rm -f minecraftum || true"

- name: Remove previous minecraftum image
  ansible.builtin.shell:
    cmd: "podman rmi -f minecraftum || true"

- name: Build a minecraftum OCI image
  ansible.builtin.shell:
    chdir: "{{ paths.minecraftum_path }}/minekraftum/"
    cmd: "podman build -t minecraftum ."
  
- name: Run minecraftum container
  ansible.builtin.shell:
    cmd: "podman run -d --name minecraftum -p 25565:25565 -v {{ paths.data_path }}:/app minecraftum"