###### Podman
- name: Setup Podman config
  shell:
    cmd: sudo loginctl enable-linger {{ podman.user }}

- name: Add Podman config file
  copy:
    src: ./containers.conf
    dest: /etc/containers/containers.conf

- name: Load new Podman config
  shell:
    cmd: podman system migrate