# - name: Installation Minecraft server
#   hosts: minecraft_vm
#   remote_user: root

#   roles:
#     - packages
#     - deploy_minecraft

- name: Installation runner server
  hosts: runner
  remote_user: root

  roles:
    - users
    - packages
    - github_runner
    - devops
